In [15]:
from google.colab import drive
import pandas as pd
import numpy as np
drive.mount('/content/drive')
purchase_data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Lab Session Data.xlsx', usecols=[0,1, 2, 3,4])
print("PURCHASE DATA:")
print(purchase_data)
data1=purchase_data.iloc[:, 1:4]
A = data1.to_numpy()
print("MATRIX A:")
print(A)
data1=purchase_data.iloc[:, 4:5]
C = data1.to_numpy()
print("MATRIX C:")
print(C)
print("DIMENSIONALITY OF VECTOR SPACE OF DATA:\n",len(A[0]))
print("NO.OF VECTOR SPACES:\n",len(A))
rank_A=np.linalg.matrix_rank(A)
print("RANK OF MATRIX A:\n",rank_A)
pseudo_inverse_A=np.linalg.pinv(A)
print("PSEUDO INVERSE OF A:\n",pseudo_inverse_A)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
PURCHASE DATA:
  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
MATRIX A:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
[['C_1' 20 6 2 386]
 ['C_2' 16 3 6 289]
 ['C_3' 27 6 2 393]
 ['C_4' 19 1 2 110]
 ['C_5' 24 4 2 280]
 